/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

public class App {

    public static void main(String[] args) {

        Linter lint = new Linter();

        lint.linter("src/main/resources/gates.js");
        lint.linter("src/main/resources/empty.js");
        lint.linter("src/main/resources/few.js");
        lint.linter("src/main/resources/many.js");
        lint.linter("src/main/resources/noerror.js");
    }

}