/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static basiclibrary.Library.*;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testDiceRolls() {
        int[] result = roll(22);
        assertTrue("Dice rolled:", result.length == 22);
    }

    @Test
    public void testContainsDuplicates(){
        int[] inputArr = {66, 66, 58, 65, 71, 57, 60};
        assertTrue("Contain Duplicates.", containsDuplicates(inputArr));
    }

    @Test
    public void testNoDuplicates(){
        int[] inputArr = {66, 67, 58, 65, 71, 57, 60};
        assertFalse("Does not Contain Duplicates.", containsDuplicates(inputArr));
    }

    @Test
    public void testCalculateAvg(){
        int[] inputArr = {1,2,3,4,5,6};
        double average = averageCalc(inputArr);
        assertTrue("Avg is: ",average == 3.5);
    }

    @Test
    public void testAverageCalcNestedArray(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        double average = averageCalcNestedArray(weeklyMonthTemperatures);
        assertEquals("LowsestAvg is: ",57.0, average, 0.01);

    }
}

